[build]
builder = "nixpacks"
watchPatterns = ["/platform/ens-resolver/**"]

[deploy]
startCommand = "bun run start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
